version: 2

updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '06:00'
      timezone: 'Europe/Brussels'
    groups:
      dev-dependencies:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '06:00'
      timezone: 'Europe/Brussels'
