name: GitHub Actions Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEY_JKS }}
        run: echo $ENCODED_STRING | base64 -di > key.jks

      - name: Signing.gradle
        env:
          ENCODED_SIGNING_GRADLE: ${{ secrets.SIGNING_GRADLE }}
        run: |
          echo $ENCODED_SIGNING_GRADLE | base64 -di > signing.gradle

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build prodRelease
        run: ./gradlew app:bundleProdRelease

      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab

      - name: Build and run tests
        run: ./gradlew test
    

