name: GitHub Actions Pipeline

on:
  push:
    branches:
      - main
      - master

# TODO:
# FIX:
#  * What went wrong:
#  A problem occurred configuring project ':app'.
#   > Failed to notify project evaluation listener.
#   > The file '/home/runner/work/Fitness-Application-Compose/Fitness-Application-Compose/local.properties' could not be found
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Android SDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: 'github'

      - name: Google Services JSON
        env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $ENCODED_STRING | base64 -di > app/google-services.json

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEY_JKS }}
        run: echo $ENCODED_STRING | base64 -di > key.jks

      - name: Signing.gradle
        env:
          ENCODED_SIGNING_GRADLE: ${{ secrets.SIGNING_GRADLE }}
        run: echo $ENCODED_SIGNING_GRADLE | base64 -di > signing.gradle

      - name: Decode Google Server Client ID and add to local.properties
        env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVER_CLIENT_ID }}
        run: |
          if [ ! -f local.properties ]; then
            touch local.properties
          fi
          echo $ENCODED_STRING | base64 -di >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build Release Bundle
        run: ./gradlew app:bundleRelease

      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab

      - name: Build and run tests
        run: ./gradlew test









    

