name: GitHub Actions Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > key.jks

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build and run tests
      run: ./gradlew test
    
    - name: SonarCloud Scan
      run: ./gradlew sonar --info
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
