name: SonarQube Analysis + Tests

on:
  push:
    branches:
      - main

jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build and run tests
      run: ./gradlew test

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        projectBaseDir: ./  # Path to your Android project's root directory
        projectName: "Fitness Application"  # Replace with your project's name
        projectKey: "tom-truyen_fitness-application"  # Replace with a unique key for your project in SonarQube
        organization: "tom-truyen"  # Replace with your SonarQube organization key
        token: ${{ secrets.SONARQUBE_AUTH_TOKEN }}  # Add your SonarQube authentication token as a secret in your repository
