name: Supabase KeepAlive Ping
description:

on:
  schedule:
    - cron: '0 0 * * 3,0' # Runs every Wednesday and Sunday at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          cd scripts/supabase/ping
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python main.py
